spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres  # Thay thế bằng tên người dùng cơ sở dữ liệu thực tế của bạn
    password: 12345678  # Thay thế bằng mật khẩu cơ sở dữ liệu thực tế của bạn
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      format_sql: true
      show_sql: true
    properties:
      hibernate:
        ddl-auto: update  # Có thể thay đổi thành "validate" hoặc "none" khi chạy trong môi trường sản xuất

  mail:
    host: smtp.gmail.com
    port: 587
    username: huyshtorm@gmail.com  # Thay thế bằng email Gmail thực tế của bạn
    password: wuec jeos hqku xkzd # Thay thế bằng mật khẩu ứng dụng Gmail của bạn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: HuySieuCapVipProGankTeamCucChat123456789Pro  # Thay thế bằng secret key thực tế của bạn
  expiration: 86400  # Thời gian hết hạn của token (86400 giây = 1 ngày)


cors:
  allowedOrigin:  '*'
  allowedMethods: '*'
  exposedHeaders: '*'
  allowCredentials: false
  corsConfiguration:  '/*'